apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: wordpress-ingress
spec:
  ingressClassName: nginx #write your IngressClassName here (do kubectl get ingressclass and copy your nginx ingress class name)
  rules:
    - host: bishnu.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: wordpress
                port:
                  number: 30010
